version: '2'
services:
    jhipsterdemo-app:
        image: jhipsterdemo
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://jhipsterdemo-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=jhipsterdemo
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jhipsterdemo-mongodb:
        extends:
            file: mongodb.yml
            service: jhipsterdemo-mongodb
